[package]
name = "funlock"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
image = "0.25.6"
pam-client = "0.5.0"
rpassword = "7.4.0"
smithay-client-toolkit = "0.19.2"
users = "0.11.0"
wayland-client = "0.31.10"
